# Generated by Django 4.2.1 on 2023-05-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='edu_school_board',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='resume',
            name='edu_school_city',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_city2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_company2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_description2',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_end_month2',
            field=models.CharField(default='Currently Working', max_length=25),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_end_year2',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_profile',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_profile_description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_start_month2',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_start_year2',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_title2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='project1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='project1_description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='resume',
            name='project2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='project2_description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='resume',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='resume',
            name='edu_degree_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='resume',
            name='edu_degree_end_month',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='resume',
            name='edu_degree_end_year',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='resume',
            name='hobby',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_description',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_end_month',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_end_year',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_start_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pin_code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(max_length=1000),
        ),
    ]
