# Generated by Django 4.2.1 on 2023-05-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_resume_edu_school_board_resume_edu_school_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='edu_degree_college_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
